# Generated by Django 5.2 on 2025-05-06 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=200)),
                ('music_director', models.CharField(max_length=200)),
                ('movie_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='songs/images/default.jpg', upload_to='songs/images/')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
