# Generated by Django 5.2 on 2025-05-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0002_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
