# Generated by Django 5.2 on 2025-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapp', '0003_remove_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio/'),
        ),
    ]
